// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByC5VEXU6YnpyIr1Mcbz4TbpzYwMsqB-M',
    appId: '1:1005919039582:web:7f0f1c451682ea5fca84cf',
    messagingSenderId: '1005919039582',
    projectId: 'tixoo-eventapp',
    authDomain: 'tixoo-eventapp.firebaseapp.com',
    storageBucket: 'tixoo-eventapp.firebasestorage.app',
    measurementId: 'G-8DL8FP1ZDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB10jdM87uP6QR-ArAwM4lXooKmtgQ71I0',
    appId: '1:1005919039582:android:f3d4ecfb606c9aa1ca84cf',
    messagingSenderId: '1005919039582',
    projectId: 'tixoo-eventapp',
    storageBucket: 'tixoo-eventapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB60M_bk-wWNo5JI2h86DVEgDrD5FRDt1k',
    appId: '1:1005919039582:ios:087808752831e961ca84cf',
    messagingSenderId: '1005919039582',
    projectId: 'tixoo-eventapp',
    storageBucket: 'tixoo-eventapp.firebasestorage.app',
    androidClientId:
        '1005919039582-mot8aqf4ccuaqe229al0nn68kutlh24s.apps.googleusercontent.com',
    iosClientId:
        '1005919039582-huk5poagr93prf4eh56bpdl34drnifr2.apps.googleusercontent.com',
    iosBundleId: 'com.drixentertainment.tixoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB60M_bk-wWNo5JI2h86DVEgDrD5FRDt1k',
    appId: '1005919039582:ios:1a57054292e91d2eca84cf',
    messagingSenderId: '1005919039582',
    projectId: 'tixoo-eventapp',
    storageBucket: 'tixoo-eventapp.firebasestorage.app',
    androidClientId:
        '1005919039582-mot8aqf4ccuaqe229al0nn68kutlh24s.apps.googleusercontent.com',
    iosClientId:
        '1005919039582-i06cioreqbbkf99585f3lvvm1dr2di29.apps.googleusercontent.com',
    iosBundleId: 'com.example.tixxo',
  );
}
